name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - ipykernel
  - tensorflow
  - nltk
  - nltk_data
  - spacy
  - spacy-model-en_core_web_md

  - pip:
    - PySastrawi
    - rasa
